//
// Constants for API interaction
//

//
// device HTTP API
//
export const REQUEST_DEVICE = 'REQUEST_DEVICE';
export const RECEIVE_DEVICE = 'RECEIVE_DEVICE';
export const REQUEST_DEVICES = 'REQUEST_DEVICES';
export const RECEIVE_DEVICES = 'RECEIVE_DEVICES';

export const CREATE_DEVICE = 'CREATE_DEVICE';
export const UPDATE_DEVICE = 'UPDATE_DEVICE';
export const DELETE_DEVICE = 'DELETE_DEVICE';

export const READ_DEVICE_DATA = 'READ_DEVICE_DATA';
export const WRITE_DEVICE_DATA = 'WRITE_DEVICE_DATA';

export const REQUEST_READ_DEVICE = 'REQUEST_READ_DEVICE';
export const RECEIVE_READ_DEVICE = 'RECEIVE_READ_DEVICE';

// device websocket API
export const SUBSCRIBE_DEVICES = 'SUBSCRIBE_DEVICE';
export const UNSUBSCRIBE_DEVICES = 'UNSUBSCRIBE_DEVICE';
export const LIVE_DATA = 'LIVE_DATA';

//
// user HTTP API
//
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const REQUEST_USER_NOTIFICATIONS = 'REQUEST_USER_NOTIFICATIONS';
export const RECEIVE_USER_NOTIFICATIONS = 'RECEIVE_USER_NOTIFICATIONS';

export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

export const SET_USER_ROLE = 'SET_USER_ROLE';
export const SET_USER_PERMISSIONS = 'SET_USER_PERMISSIONS';
export const SET_USER_NOTIFICATIONS = 'SET_USER_NOTIFICATIONS';

// current userService
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

// websocket information
export const WEBSOCKET_CONNECTED = 'WEBSOCKET_CONNECTED';
export const WEBSOCKET_CONNECTING = 'WEBSOCKET_CONNECTING';
export const WEBSOCKET_SHOULD_CONNECT = 'WEBSOCKET_SHOULD_CONNECT';
export const WEBSOCKET_INVALID_AUTH = 'WEBSOCKET_INVALID_AUTH';
export const WEBSOCKET_LIVE_DATA = 'WEBSOCKET_LIVE_DATA';
export const WEBSOCKET_DISCONNECTED = 'WEBSOCKET_DISCONNECTED';
